version: '3.8'
services:
  sd_service:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: sd_image
    container_name: sd_container
    # user: ${UID}:${GID}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ports:
      - "${SERVICE_PORT}:7860"
    volumes:
      - "${MODEL_PATH}:/app/stable-diffusion-webui/models"
      - "${USER_DATA_PATH}:/app/user_data"
    restart: unless-stopped
